/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef OHOS_ABILITY_BASE_WANT_PARAMS_WRAPPER_JSON_H
#define OHOS_ABILITY_BASE_WANT_PARAMS_WRAPPER_JSON_H

#include <string>

#include "want_params.h"

namespace OHOS {
namespace AAFwk {
namespace WantParamWrapperJson {
/**
 * @brief Envelope key of the WantParams JSON wrapper format.
 */
constexpr char ENVELOPE_KEY[] = "ohos.want.paramsStringEnvelope";

/**
 * @brief Parses a WantParams string generated by Serialize.
 *
 * This function is the upgrade path for the legacy WantParamWrapper::Parse /
 * WantParamWrapper::ToString format. The legacy format is assembled by string
 * concatenation, does not escape keys or values, embeds typeId as ad-hoc text,
 * and scans quotes/braces manually. Therefore strings containing quotes,
 * backslashes, control characters, or delimiter-like text may be truncated,
 * rejected, or restored incorrectly by the legacy parser.
 *
 * This function only supports the WantParams JSON envelope format generated by
 * Serialize. It does not support arbitrary JSON strings or JSON strings produced
 * by other serializers. The envelope key must be ENVELOPE_KEY. The combined
 * recursive nesting depth across WantParams and Array values must not exceed
 * 100. The top-level WantParams starts at depth 0. Non-WantParams values,
 * including Array values, must be encoded as JSON strings; nested WantParams
 * values must be encoded as JSON objects.
 *
 * This parser is strict: malformed JSON, invalid or unknown typeId, non-string
 * scalar values, unsupported scalar type restoration, trailing members outside
 * the envelope, VALUE_TYPE_NULL typed values, and combined WantParams/Array
 * nesting beyond the depth limit all fail without updating out. Each typed-value
 * object must resolve to exactly one typeId member after JSON object parsing.
 * Typed-value objects with zero members or multiple different typeId members
 * fail. Duplicate member names follow JSON object and WantParams map overwrite
 * semantics.
 *
 * If the data source may contain multiple formats, callers should use
 * HasEnvelope to select this parser path. Parse also validates the envelope and
 * returns false when it is missing.
 *
 * @param text Indicates the string to parse.
 * @param out Indicates the parsed WantParams. The value is updated only when
 * parsing succeeds.
 * @return Returns true if the string is parsed successfully; returns false
 * otherwise.
 */
bool Parse(const std::string &text, WantParams &out);

/**
 * @brief Checks whether a string starts with the exact WantParams JSON wrapper envelope.
 *
 * This function is only used to select the parser path. It matches the exact
 * envelope prefix emitted by Serialize and does not allow whitespace before or
 * inside the prefix. It does not validate the complete JSON content.
 *
 * @param text Indicates the string to check.
 * @return Returns true if the wrapper envelope is detected; returns false
 * otherwise.
 */
bool HasEnvelope(const std::string &text);

/**
 * @brief Serializes WantParams to the WantParams JSON wrapper format.
 *
 * This function is the serialization-side upgrade for the legacy
 * WantParamWrapper::ToString format. It uses a real JSON object with ENVELOPE_KEY
 * instead of raw string concatenation, so keys, typeId strings, scalar values,
 * backslashes, quotes, control characters, and nested WantParams delimiters are
 * represented through JSON escaping instead of the legacy parser's delimiter
 * conventions.
 *
 * This function only serializes WantParams. The combined recursive nesting depth
 * across WantParams and Array values must not exceed 100. The top-level
 * WantParams starts at depth 0. Types still rely on WantParams::GetDataType and
 * WantParams::GetStringByType; null values and values that cannot be represented
 * by those helper APIs are skipped, matching existing WantParams unwrap behavior.
 *
 * The output uses the format
 * {"ohos.want.paramsStringEnvelope":{"key":{"typeId":"value"}}}.
 * For nested WantParams, the typeId is "101" and the value is a JSON object,
 * for example {"ohos.want.paramsStringEnvelope":{"key":{"101":{"child":{"9":"value"}}}}}.
 *
 * @param wp Indicates the WantParams to serialize.
 * @param out Indicates the serialized string. The value is updated only when
 * serialization succeeds.
 * @return Returns true if serialization succeeds; returns false otherwise.
 */
bool Serialize(const WantParams &wp, std::string &out);
}  // namespace WantParamWrapperJson
}  // namespace AAFwk
}  // namespace OHOS

#endif  // OHOS_ABILITY_BASE_WANT_PARAMS_WRAPPER_JSON_H
