/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef OHOS_ABILITY_BASE_WANT_PARAMS_WRAPPER_JSON_H
#define OHOS_ABILITY_BASE_WANT_PARAMS_WRAPPER_JSON_H

#include <string>

#include "want_params.h"

namespace OHOS {
namespace AAFwk {
namespace WantParamWrapperJson {
/**
 * @brief Envelope key of the WantParams JSON wrapper format.
 */
constexpr char ENVELOPE_KEY[] = "ohos.want.paramsStringEnvelope";

/**
 * @brief Defines how JSON conversion handles unsupported parameter types.
 */
enum class UnsupportedTypePolicy {
    FAIL,
    SKIP,
};

/**
 * @brief Parses a WantParams string generated by Serialize.
 *
 * This function is the upgrade path for the legacy WantParamWrapper::Parse /
 * WantParamWrapper::ToString format. The legacy format is assembled by string
 * concatenation, does not escape keys or values, embeds typeId as ad-hoc text,
 * and scans quotes/braces manually. Therefore strings containing quotes,
 * backslashes, control characters, or delimiter-like text may be truncated,
 * rejected, or restored incorrectly by the legacy parser.
 *
 * This overload uses UnsupportedTypePolicy::SKIP. Use the policy overload when
 * unsupported values should fail the complete conversion.
 *
 * This function only supports the WantParams JSON envelope format generated by
 * Serialize. It does not support arbitrary JSON strings or JSON strings produced
 * by other serializers. The envelope key must be ENVELOPE_KEY. The combined
 * recursive nesting depth across WantParams and Array values must not exceed
 * 100. The top-level WantParams starts at depth 0. Scalar values are encoded as
 * JSON strings and nested WantParams values are encoded as JSON objects. Array
 * values use an object whose only member declares the element type and whose
 * value is a JSON array. Array element types 1 through 9 use the same canonical
 * string representation as scalar WantParams values. Element type 101 represents
 * WantParams and element type 102 represents Array, so nested Arrays may terminate
 * in either scalar or WantParams arrays.
 * Legacy type-102 strings and the obsolete elementType/items object are rejected.
 * TypeId member names must use canonical decimal form without redundant leading
 * zeros, a leading plus sign, or whitespace.
 *
 * Unsupported numeric typeIds and Arrays with unsupported element types are
 * omitted by default. Other invalid input is handled strictly: malformed JSON,
 * invalid or non-canonical typeId strings, non-string scalar values or scalar
 * Array items, invalid Array schema or item, unsupported scalar type restoration,
 * trailing members outside the envelope, and combined WantParams/Array nesting
 * beyond the depth limit all fail without updating out. Each typed-value object
 * must resolve to exactly one typeId member after JSON object parsing. Typed-value
 * objects with zero members or multiple different typeId members fail. Duplicate
 * member names follow JSON object and WantParams map overwrite semantics. Scalar
 * strings must match the canonical representation generated by
 * WantParams::GetStringByType.
 *
 * If the data source may contain multiple formats, callers should use
 * HasEnvelope to select this parser path. Parse also validates the envelope and
 * returns false when it is missing.
 *
 * @param text Indicates the string to parse.
 * @param out Indicates the parsed WantParams. The value is updated only when
 * parsing succeeds.
 * @return Returns true if the string is parsed successfully; returns false
 * otherwise.
 */
bool Parse(const std::string &text, WantParams &out);

/**
 * @brief Parses a WantParams JSON wrapper using the specified unsupported-type policy.
 *
 * Unsupported numeric typeIds and arrays with unsupported element types either
 * fail the complete conversion or are omitted according to policy. Malformed
 * JSON, invalid or non-canonical typeId strings, invalid supported values, and
 * depth violations always fail without updating out. Unsupported Array element
 * types propagate to the owning named Array parameter; individual Array items
 * are not removed. Skipped values are reported by warning logs.
 *
 * @param text Indicates the string to parse.
 * @param out Indicates the parsed WantParams. The value is updated only when
 * parsing succeeds.
 * @param policy Indicates how unsupported types are handled.
 * @return Returns true if the string is parsed successfully; returns false
 * otherwise.
 */
bool Parse(const std::string &text, WantParams &out, UnsupportedTypePolicy policy);

/**
 * @brief Checks whether a string starts with the exact WantParams JSON wrapper envelope.
 *
 * This function is only used to select the parser path. It matches the exact
 * envelope prefix emitted by Serialize and does not allow whitespace before or
 * inside the prefix. It does not validate the complete JSON content.
 *
 * @param text Indicates the string to check.
 * @return Returns true if the wrapper envelope is detected; returns false
 * otherwise.
 */
bool HasEnvelope(const std::string &text);

/**
 * @brief Serializes WantParams to the WantParams JSON wrapper format.
 *
 * This function is the serialization-side upgrade for the legacy
 * WantParamWrapper::ToString format. It uses a real JSON object with ENVELOPE_KEY
 * instead of raw string concatenation, so keys, typeId strings, scalar values,
 * backslashes, quotes, control characters, and nested WantParams delimiters are
 * represented through JSON escaping instead of the legacy parser's delimiter
 * conventions. WantParams and nested Array elements are recursively encoded as
 * JSON objects instead of using a legacy Array string format.
 *
 * This overload uses UnsupportedTypePolicy::SKIP. Use the policy overload when
 * unsupported values should fail the complete conversion.
 *
 * This function only serializes WantParams. The combined recursive nesting depth
 * across WantParams and Array values must not exceed 100. The top-level
 * WantParams starts at depth 0. Types still rely on WantParams::GetDataType and
 * WantParams::GetStringByType. Null values are skipped. Non-null values that
 * cannot be represented by those helper APIs are treated as unsupported.
 *
 * Scalar and nested WantParams output uses the format
 * {"ohos.want.paramsStringEnvelope":{"key":{"typeId":"value"}}}.
 * For nested WantParams, the typeId is "101" and the value is a JSON object,
 * for example {"ohos.want.paramsStringEnvelope":{"key":{"101":{"child":{"9":"value"}}}}}.
 * For a scalar array, typeId is "102" and the value declares the scalar element
 * type, for example {"1":["true","false"]} for a Boolean array. For a
 * WantParams array, typeId is "102" and the value is
 * {"101":[...]}, where each item is a WantParams JSON object without another
 * envelope. For an Array of Arrays, the value is {"102":[...]}, where each item
 * is another Array object. Scalar Array items are encoded as JSON strings using
 * the canonical representation generated by WantParams::GetStringByType.
 *
 * @param wp Indicates the WantParams to serialize.
 * @param out Indicates the serialized string. The value is updated only when
 * serialization succeeds.
 * @return Returns true if serialization succeeds; returns false otherwise.
 */
bool Serialize(const WantParams &wp, std::string &out);

/**
 * @brief Serializes WantParams using the specified unsupported-type policy.
 *
 * Unsupported parameter types either fail the complete conversion or are
 * omitted according to policy. Invalid supported values and depth violations
 * always fail without updating out. Skipped values are reported by warning
 * logs. If all parameters are skipped, serialization succeeds with an empty
 * envelope value. Null values are silently omitted regardless of policy.
 * Unsupported Array element types propagate to the owning named Array parameter;
 * individual Array items are not removed.
 *
 * @param wp Indicates the WantParams to serialize.
 * @param out Indicates the serialized string. The value is updated only when
 * serialization succeeds.
 * @param policy Indicates how unsupported types are handled.
 * @return Returns true if serialization succeeds; returns false otherwise.
 */
bool Serialize(const WantParams &wp, std::string &out, UnsupportedTypePolicy policy);
}  // namespace WantParamWrapperJson
}  // namespace AAFwk
}  // namespace OHOS

#endif  // OHOS_ABILITY_BASE_WANT_PARAMS_WRAPPER_JSON_H
